### PR TITLE
Update README-OpenShift.md

### LINKED ISSUE #56: OpenSift cleanup steps needs update
The OpenShift deployment Cleanup steps needs to be updated to remove the following resources:

service/get-started-node
buildconfig.build.openshift.io/get-started-node
build.build.openshift.io/get-started-node-1
imagestream.image.openshift.io/get-started-node

### PR DESCRIPTION
**Pull request by akihikokuroda**
Adding resources to be cleaned up for OpenShift. 

fix: https://github.com/IBM-Cloud/get-started-node/issues/56

### CODE REVIEW

**Review by hickeyma — CHANGES_REQUESTED** [review]
Tested this and it looks good, thanks @akihikokuroda. Just one thing, I think this line is no longer required because you delete the `buildconfig` now:

`oc get pods --no-headers=true | awk '/node-[0-9]{1,}-build/{print $1}' |  xargs oc delete pods`

Do you mind confirming this?

**Comment by akihikokuroda** [comment]
@hickeyma Yes, you are right.  The build pod is owned by the build instance that is owned by the buildconfig instance. So deleting the buildconfig instance deletes the build pod.
I'll remove the step.

Thanks!

**Review by hickeyma — APPROVED** [review]
LGTM, thanks @akihikokuroda

**Comment by hickeyma** [comment]
@kevin-ortega If you get a chancel can you take a look. Thanks.

**Review by kevin-ortega — APPROVED** [review]

**Comment by kevin-ortega** [comment]
Approved and merged

**Comment by hickeyma** [comment]
Thanks @kevin-ortega

**Pull request merged**
